[package]
name = "ankra-wayland"
version = "0.1.0"
edition = "2021"

[lib]
name = "ankra_wayland"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
libankra = { path = "../libankra" }
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client"] }
wayland-protocols-misc = { version = "0.3", features = ["client"] }
mio = { version = "1.0", features = ["os-poll", "os-ext"] }
rustix = { version = "0.38", features = ["time", "fs"] }
libc = "0.2.82"
log = "0.4.17"
